### ISSUE TITLE
terraform-provider-sysdig_v0.5.40 crashes

### ISSUE THREAD

**Issue by omaen** [sysdiglabs/terraform-provider-sysdig#209]
Hi,

I'm trying to use this provider to create these three resources, but it crashes when i try to run `terraform apply`.
- `sysdig_secure_notification_channel_slack`
- `sysdig_secure_list`
- `sysdig_secure_rule_falco`

I get these errors and a stacktrace:
```
│ Error: Plugin did not respond
│
│   with sysdig_secure_notification_channel_slack.slack_alarm_channel,
│   on main.tf line 13, in resource "sysdig_secure_notification_channel_slack" "slack_alarm_channel":
│   13: resource "sysdig_secure_notification_channel_slack" "slack_alarm_channel" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: cannot verify credentials
│
│   with sysdig_secure_list.custom_system_namespaces,
│   on main.tf line 24, in resource "sysdig_secure_list" "custom_system_namespaces":
│   24: resource "sysdig_secure_list" "custom_system_namespaces" {
│
╵
╷
│ Error: cannot verify credentials
│
│   with sysdig_secure_rule_falco.actions_runner_system,
│   on main.tf line 38, in resource "sysdig_secure_rule_falco" "actions_runner_system":
│   38: resource "sysdig_secure_rule_falco" "actions_runner_system" {
│
╵

Stack trace from the terraform-provider-sysdig_v0.5.40 plugin:

panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation

goroutine 81 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.DiagsToProto({0x14000884f00?, 0x1, 0x140005a9708?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:72 +0x268
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.AppendProtoDiag({0x0, 0x0, 0x0}, {0x1018998c0?, 0x14000514768?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:25 +0x74
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000126348, {0x1019915b8, 0x140000e8440}, 0x140009b22d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:978 +0xb54
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000250700, {0x101991660?, 0x140009ca780?}, 0x140009a65b0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x210
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x101957040?, 0x14000250700}, {0x101991660, 0x140009ca780}, 0x140009d6240, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000296700, {0x101995660, 0x14000500820}, 0x140009d47e0, 0x140000d5a70, 0x101ef26c0, 0x0)
	google.golang.org/grpc@v1.43.0/server.go:1282 +0xb28
google.golang.org/grpc.(*Server).handleStream(0x14000296700, {0x101995660, 0x14000500820}, 0x140009d47e0, 0x0)
	google.golang.org/grpc@v1.43.0/server.go:1616 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.43.0/server.go:921 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.43.0/server.go:919 +0x290

Error: The terraform-provider-sysdig_v0.5.40 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Using:
```
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.40.0
+ provider registry.terraform.io/sysdiglabs/sysdig v0.5.40
```

Initially tested on a GitHub Actions runner running `ubuntu-latest` with latest terraform version.

**Comment by wideawakening** [comment]
addressed provider authentication clarification. hope that clarifies bit more :)
https://github.com/sysdiglabs/terraform-provider-sysdig/pull/212
