### ISSUE TITLE
Provider v0.5.43 crashes after appending exception to managed rule

### ISSUE THREAD

**Issue by omaen** [sysdiglabs/terraform-provider-sysdig#223]
Hi,

I tried the new version that would allow the creation of custom exceptions to existing managed rules in Sysdig Secure. The creation of these rules were successful, but the next time I tried to do ta `terraform plan` while working on a standalone custom rule, the provider crashes with this exception message:
```
The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-sysdig_v0.5.43 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc743ed]

goroutine 42 [running]:
github.com/draios/terraform-provider-sysdig/sysdig.resourceSysdigRuleFalcoRead({0x10a7328, 0xc0006e14a0}, 0xc0006e8900, {0xd76da0?, 0xc000598690})
	github.com/draios/terraform-provider-sysdig/sysdig/resource_sysdig_secure_rule_falco.go:143 +0x36d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00009f960, {0x10a7360, 0xc0005724e0}, 0xd?, {0xd76da0, 0xc000598690})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00009f960, {0x10a7360, 0xc0005724e0}, 0xc0006e7380, {0xd76da0, 0xc000598690})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002119e0, {0x10a7360?, 0xc0005723c0?}, 0xc0006d8140)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0004a8d20, {0x10a7360?, 0xc0006fbdd0?}, 0xc000762c00)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xdea260?, 0xc0004a8d20}, {0x10a7360, 0xc0006fbdd0}, 0xc000598000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00045e3c0, {0x10ab560, 0xc00028aea0}, 0xc0005f65a0, 0xc00022f890, 0x1646f30, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc00045e3c0, {0x10ab560, 0xc00028aea0}, 0xc0005f65a0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-sysdig_v0.5.43 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

I tried to debug this issue myself, but couldn't find a solution to the problem. The provider crashes somewhere in `resourceSysdigRuleFalcoRead` when fetching the rule. It seems like the ID of the rules has changed in Sysdig Secure while the Terraform state still references the old values. Not sure if this is the root cause, but I get these error logs:
```
{"message":"Failed to find a rule with id: 10005986","referenceId":"8e7c2f02-b06f-42a1-ad3b-7408021ae3d5"}: timestamp=2022-12-12T09:31:45.608+0100
{"message":"Failed to find a rule with id: 10005988","referenceId":"cac28402-ab8d-4aef-a35d-3a1399619e61"}: timestamp=2022-12-12T09:31:45.608+0100
{"message":"Failed to find a rule with id: 10005987","referenceId":"243bcf5f-fe3d-4012-b275-56f70d33efb5"}: timestamp=2022-12-12T09:31:45.613+0100
```

Let me know if you are able to reproduce this issue with this rule for example:
```
resource "sysdig_secure_rule_falco" "create_hidden_files_directories" {
  name   = "Create Hidden Files or Directories"
  append = true

  exceptions {
    name   = "proc_fd_startswith_endswith"
    fields = ["proc.name", "fd.name"]
    comps  = ["=", "glob"]
    values = jsonencode([
      [
        "runc",
        "/run/containerd/io.containerd.runtime.v2.task/k8s.io/*/.instana*.pid"
      ]
    ])
  }
}
```

**Comment by tembleking** [comment]
Hey @omaen thanks for reporting it, this issue seems to be that the API is not returning a condition and therefore it's kept as a nil pointer, because of the `omitempty`. This change will avoid the nil pointer dereference that affects you. The empty condition is valid because you are only appending an exception.
