### ISSUE TITLE
The terraform-provider-sysdig_v1.7.0 plugin crashed

### ISSUE THREAD

**Issue by dellison-castlight** [sysdiglabs/terraform-provider-sysdig#367]
When running the Terraform Plan through Cloud Build in GCP, we encountered the following error: 
```
│ Error: Plugin did not respond
│ 
│   with module.sysdig_agent_org_level.data.sysdig_secure_connection.current,
│   on .terraform/modules/sysdig_agent_org_level/examples/organization-org_compliance/data.tf line 3, in data "sysdig_secure_connection" "current":
│    3: data "sysdig_secure_connection" "current" {}
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.sysdig_agent_org_level.module.cloud_bench_workload_identity[0].module.trust_relationship.data.sysdig_secure_trusted_cloud_identity.trusted_identity,
│   on .terraform/modules/sysdig_agent_org_level/modules/services/cloud-bench-workload-identity/trust_relationship/main.tf line 9, in data "sysdig_secure_trusted_cloud_identity" "trusted_identity":
│    9: data "sysdig_secure_trusted_cloud_identity" "trusted_identity" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-sysdig_v1.7.0 plugin:

fatal error: concurrent map writes

goroutine 56 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0xc0006958f0, {0xc000697c60, 0x1, 0x1})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_reader_diff.go:81 +0x59f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc00007eb80, {0xc000697c60, 0x1, 0x1}, {0xe74682, 0x3})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_reader_multi.go:45 +0x146
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc00014a600, {0xc000697c60, 0x1, 0x1}, 0x8?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:550 +0x1b3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getRaw(0x49880a?, {0xe80d7e?, 0xc00055d128?}, 0xa?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:119 +0x95
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).GetOk(0xc00055d1d0?, {0xe80d7e?, 0xc00055d230?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:85 +0x38
github.com/draios/terraform-provider-sysdig/sysdig.getSysdigSecureVariables(0x70?)
	github.com/draios/terraform-provider-sysdig/sysdig/sysdig_clients.go:93 +0x2e
github.com/draios/terraform-provider-sysdig/sysdig.(*sysdigClients).sysdigSecureClientV2(0xc0001401c0)
	github.com/draios/terraform-provider-sysdig/sysdig/sysdig_clients.go:198 +0xc5
github.com/draios/terraform-provider-sysdig/sysdig.getSecureCloudAccountClient(...)
	github.com/draios/terraform-provider-sysdig/sysdig/resource_sysdig_secure_cloud_account.go:73
github.com/draios/terraform-provider-sysdig/sysdig.dataSourceSysdigSecureTrustedCloudIdentityRead({0x10f0048?, 0xc000695860?}, 0x0?, {0xe0e2c0?, 0xc0001401c0?})
	github.com/draios/terraform-provider-sysdig/sysdig/data_source_sysdig_secure_trusted_cloud_identity.go:56 +0x73
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0002920e0, {0x10f0080, 0xc000695110}, 0xd?, {0xe0e2c0, 0xc0001401c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0002920e0, {0x10f0080, 0xc000695110}, 0xc000549900, {0xe0e2c0, 0xc0001401c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0001d3920, {0x10f0080?, 0xc000694ff0?}, 0xc00007e8e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1195 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000496dc0, {0x10f0080?, 0xc000694660?}, 0xc000504a50)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:658 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xe43ae0?, 0xc000496dc0}, {0x10f0080, 0xc000694660}, 0xc000542b60, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b8000, {0x10f4140, 0xc000516680}, 0xc00061eb40, 0xc00029c5a0, 0x16c23f0, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001b8000, {0x10f4140, 0xc000516680}, 0xc00061eb40, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc000098c60)
	github.com/hashicorp/go-plugin@v1.4.8/server.go:471 +0x1505
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0xe78f24, 0x8}, 0xc0002b39d0, {0x0, 0x0, 0x0})
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:312 +0xc0a
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf5serverServe(0xc000098c00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/plugin/serve.go:185 +0x4d9
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc000098c00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/plugin/serve.go:125 +0x18d
main.main()
	github.com/draios/terraform-provider-sysdig/main.go:10 +0x34

goroutine 15 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x0?)
	github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:121 +0x67
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc0002d2230)
	github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:411 +0x44
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	github.com/hashicorp/go-plugin@v1.4.8/grpc_server.go:85 +0x46a

goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x7fa6b2bbaef0, 0x72)
	runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000099020?, 0xc00048d000?, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000099020, {0xc00048d000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc000012040, {0xc00048d000?, 0x400?, 0xd44060?})
	os/file.go:118 +0x5e
bufio.(*Reader).Read(0xc0004b8740, {0xc0000dc400, 0x400, 0x0?})
	bufio/bufio.go:237 +0x1bb
github.com/hashicorp/go-plugin.copyChan({0x10f6c58, 0xc00046d7a0}, 0x0?, {0x10eba60?, 0xc000012040?})
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:37 +0xf5

goroutine 49 [IO wait]:
internal/poll.runtime_pollWait(0x7fa6b2bbad10, 0x72)
	runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0000990e0?, 0xc000118000?, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000990e0, {0xc000118000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc000012050, {0xc000118000?, 0x400?, 0xd44060?})
	os/file.go:118 +0x5e
bufio.(*Reader).Read(0xc0004b8f40, {0xc0000dc800, 0x400, 0x0?})
	bufio/bufio.go:237 +0x1bb
github.com/hashicorp/go-plugin.copyChan({0x10f6c58, 0xc00046d7a0}, 0x0?, {0x10eba60?, 0xc000012050?})
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:38 +0x185

goroutine 23 [syscall]:

Error: The terraform-provider-sysdig_v1.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Let me know if you need any other details. 

EDIT: I forgot to mention but we have been using this provider and it has been working fine, we just randomly got this error while making unrelated code changes, and the second time we ran the plan it worked.

**Comment by filiptubic** [comment]
Hey @dellison-castlight, so this issue is not happening again if you invoke plan? You just got this error one time randomly?
